# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'ProductivityApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProductivityApp
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 5.0.0-rc.2'
  pod 'Highcharts', '~> 7.2.0'
  pod 'SCLAlertView'
  pod 'SwiftyGif'

end
